### ISSUE TITLE
working example of html page for this wasm

### ISSUE THREAD

**Issue by rahulamalkar** [insane-jo/talib-wasm#10]
Hi @insane-jo ,
i seek your help in creating a working html page were we can use this wasm lib.

**Comment by insane-jo** [comment]
Hi @rahulamalkar . You need to use webpack to build your javascript app. Do you use webpack?

**Comment by rahulamalkar** [comment]
Nope @insane-jo , i am new to it.

**Comment by insane-jo** [comment]
@rahulamalkar , this package does not contain standalone version. But you can do like that:
1. Add file to your page `talib-wasm/build/talib.js` like that: `<script type="text/javascript" src="file:///Users/myuser/Documents/own-projects/talib-wasm-npm/build/talib.js"/>`
2. Than you can use `Module.ready.then(() => { ${your code here} });`
