### ISSUE TITLE
Source code please

### ISSUE THREAD

**Issue by sohailalam2** [insane-jo/talib-wasm#2]
Hi, Jo (assuming that's your name) :)

Could you please share the source code of how you generated the main.js from wasm?

I would love to know more about how you achieved that.

Thanks

**Comment by insane-jo** [comment]
@sohailalam2, Sorry for my long answer. 
This package was a part of my another project - trade robots builder platform. May be this was one of dependencies inside project. But I think - this can be artifacts inside emscripten. 
Anyway - you can see inside [commit](https://github.com/insane-jo/talib-wasm/commit/41eb3315179ce83a86dfefe45e00d977f625a59f) with build scripts.
