### ISSUE TITLE
Why are there createSocket commands in source?

### ISSUE THREAD

**Issue by pennyfx** [insane-jo/talib-wasm#3]
This is a cool concept, but as the other issue said, we need the source code and build process.    I can't tell if these references are benign or not.  There are also references to indexdb.   Talib is only a collection of math functions, so I can't imagine why this other stuff is included.  

```
createSocket:function(A,I,g){
```

```
indexedDB:function(){return window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB},DB_NAME:function(){return"EM_FS_"+window.location.pathname},DB_VERSION:20,DB_STORE_NAME:"FILE_DATA",saveFilesToDB:function(A,I,g){I=I||function(){},g=g||function(){};var C=JA.indexedDB()
```

**Comment by insane-jo** [comment]
Sorry for my long answer. 
This package was a part of my another project - trade robots builder platform. May be this was one of dependencies inside project. But I think - this can be artifacts inside emscripten. 
Anyway - you can see inside [commit](https://github.com/insane-jo/talib-wasm/commit/41eb3315179ce83a86dfefe45e00d977f625a59f) with build scripts.
