### ISSUE TITLE
Results of STOCH and STOCHF seems to be wrong

### ISSUE THREAD

**Issue by BoonRmaschine** [insane-jo/talib-wasm#8]
Hi there,

at first I thank you for the work you've done. I really appreciate your effort.
I am using your library to calculate different indicators from real data. 

But using the STOCH and STOCHF indicator, the calculated results seem to be not equal to those of other indicator sources. I tried to debug into the library with the Chrome Canary C/C++ DevTools to see where the problem is, but unfortunately it is not able to show the values of the variables.

I forked the project and wrote a test to point out the problem in the best way possible. Please see https://github.com/BoonRmaschine/talib-wasm/blob/bd12d111a2c8dad5fd3b9bf62cd5951d6d49a5fd/test/init.spec.ts#L18 for reference.

May you be able to figure out what am I going wrong there? Or does I indeed found a bug here?

Thank you for your time.

**Comment by insane-jo** [comment]
Hello, @BoonRmaschine .
Sorry, but I haven't write logic of indicators by myself. I build it from source ta-lib.org. Can you check logic of basic function in C and tell me what is wrong?

It can be found here: `node_modules/talib/src/lib/src/ta_func/ta_STOCHF.c`

**Comment by BoonRmaschine** [comment]
Hi @insane-jo,

I know that you are utilize the original C/C++ talib. 
To write a test in plain C/C++ is the next todo on my list. Just wanted to hear if you have another tip for me. 

Is the stochastic oscillator working on your side?

I'll write an update if I have findings to share. 

Thanks.

**Comment by insane-jo** [comment]
No, I have the same issue. I'll try to debug func call in original library and check what happens. I'll left this issue open.

**Comment by BoonRmaschine** [comment]
Hey there,

I found some time to figure out a solutoin. So please have a look at my PR #9 which solves the issue.

The library functions should all work now.

**Comment by insane-jo** [comment]
@BoonRmaschine thx! That works fine!

**Comment by insane-jo** [comment]
@BoonRmaschine 
npm package updated to version 3.0.1
Feel free to update your dependency
